name: Docker Image CI

on:
  push:
    tags:
    - '*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag pysolarmanproxy:${{github.ref_name}} --build-arg PYSOLARMAN_VERSION=${{github.ref_name}} .
